version: "3.9"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  messageprocessor:
    environment:
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=dotnet
      - EventHubName=fmdevwestus2iothub
      - IoTHubConnectionString=Endpoint=sb://iothub-ns-fmdevwestu-23622869-21c8f3a31b.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=pUSx3ddQy7bvG9vqjrgSfCrO/X/Tk4/MybPpWqVDj/s=;EntityPath=fmdevwestus2iothub
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - azurite
